/*
 * This file is generated by jOOQ.
*/
package BoBaPop.Model;


import BoBaPop.Model.tables.Bills;
import BoBaPop.Model.tables.Customers;
import BoBaPop.Model.tables.Customertypes;
import BoBaPop.Model.tables.Drinks;
import BoBaPop.Model.tables.Drinktypes;
import BoBaPop.Model.tables.Items;
import BoBaPop.Model.tables.Tables;
import BoBaPop.Model.tables.VwBilldetails;
import BoBaPop.Model.tables.VwItems;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Coffeemilkteamanager extends SchemaImpl {

    private static final long serialVersionUID = 1708169195;

    /**
     * The reference instance of <code>coffeemilkteamanager</code>
     */
    public static final Coffeemilkteamanager COFFEEMILKTEAMANAGER = new Coffeemilkteamanager();

    /**
     * InnoDB free: 6144 kB; (`CustomerID`) REFER `coffeemilkteamanager/customers`(`Cus
     */
    public final Bills BILLS = BoBaPop.Model.tables.Bills.BILLS;

    /**
     * InnoDB free: 6144 kB; (`CustomerTypeID`) REFER `coffeemilkteamanager/customertyp
     */
    public final Customers CUSTOMERS = BoBaPop.Model.tables.Customers.CUSTOMERS;

    /**
     * InnoDB free: 6144 kB
     */
    public final Customertypes CUSTOMERTYPES = BoBaPop.Model.tables.Customertypes.CUSTOMERTYPES;

    /**
     * InnoDB free: 6144 kB; (`DrinkTypeID`) REFER `coffeemilkteamanager/drinktypes`(`D
     */
    public final Drinks DRINKS = BoBaPop.Model.tables.Drinks.DRINKS;

    /**
     * InnoDB free: 6144 kB
     */
    public final Drinktypes DRINKTYPES = BoBaPop.Model.tables.Drinktypes.DRINKTYPES;

    /**
     * InnoDB free: 6144 kB; (`BillID`) REFER `coffeemilkteamanager/bills`(`BillID`); (
     */
    public final Items ITEMS = BoBaPop.Model.tables.Items.ITEMS;

    /**
     * InnoDB free: 6144 kB
     */
    public final Tables TABLES = BoBaPop.Model.tables.Tables.TABLES;

    /**
     * VIEW
     */
    public final VwBilldetails VW_BILLDETAILS = BoBaPop.Model.tables.VwBilldetails.VW_BILLDETAILS;

    /**
     * VIEW
     */
    public final VwItems VW_ITEMS = BoBaPop.Model.tables.VwItems.VW_ITEMS;

    /**
     * No further instances allowed
     */
    private Coffeemilkteamanager() {
        super("coffeemilkteamanager", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Bills.BILLS,
            Customers.CUSTOMERS,
            Customertypes.CUSTOMERTYPES,
            Drinks.DRINKS,
            Drinktypes.DRINKTYPES,
            Items.ITEMS,
            Tables.TABLES,
            VwBilldetails.VW_BILLDETAILS,
            VwItems.VW_ITEMS);
    }
}
