/*
 * This file is generated by jOOQ.
*/
package BoBaPop.Model;


import BoBaPop.Model.routines.Chargedgrandtotal;
import BoBaPop.Model.routines.Chargedtotalonitem;
import BoBaPop.Model.routines.Isstaying;
import BoBaPop.Model.routines.SpGetdatasortedby;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in coffeemilkteamanager
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>coffeemilkteamanager.ChargedGrandTotal</code>
     */
    public static Double chargedgrandtotal(Configuration configuration, Integer billId) {
        Chargedgrandtotal f = new Chargedgrandtotal();
        f.setBillId(billId);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>coffeemilkteamanager.ChargedGrandTotal</code> as a field.
     */
    public static Field<Double> chargedgrandtotal(Integer billId) {
        Chargedgrandtotal f = new Chargedgrandtotal();
        f.setBillId(billId);

        return f.asField();
    }

    /**
     * Get <code>coffeemilkteamanager.ChargedGrandTotal</code> as a field.
     */
    public static Field<Double> chargedgrandtotal(Field<Integer> billId) {
        Chargedgrandtotal f = new Chargedgrandtotal();
        f.setBillId(billId);

        return f.asField();
    }

    /**
     * Call <code>coffeemilkteamanager.ChargedTotalOnItem</code>
     */
    public static Double chargedtotalonitem(Configuration configuration, Integer billId, Integer drinkId) {
        Chargedtotalonitem f = new Chargedtotalonitem();
        f.setBillId(billId);
        f.setDrinkId(drinkId);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>coffeemilkteamanager.ChargedTotalOnItem</code> as a field.
     */
    public static Field<Double> chargedtotalonitem(Integer billId, Integer drinkId) {
        Chargedtotalonitem f = new Chargedtotalonitem();
        f.setBillId(billId);
        f.setDrinkId(drinkId);

        return f.asField();
    }

    /**
     * Get <code>coffeemilkteamanager.ChargedTotalOnItem</code> as a field.
     */
    public static Field<Double> chargedtotalonitem(Field<Integer> billId, Field<Integer> drinkId) {
        Chargedtotalonitem f = new Chargedtotalonitem();
        f.setBillId(billId);
        f.setDrinkId(drinkId);

        return f.asField();
    }

    /**
     * Call <code>coffeemilkteamanager.IsStaying</code>
     */
    public static Byte isstaying(Configuration configuration, Integer tableid) {
        Isstaying f = new Isstaying();
        f.setTableid(tableid);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>coffeemilkteamanager.IsStaying</code> as a field.
     */
    public static Field<Byte> isstaying(Integer tableid) {
        Isstaying f = new Isstaying();
        f.setTableid(tableid);

        return f.asField();
    }

    /**
     * Get <code>coffeemilkteamanager.IsStaying</code> as a field.
     */
    public static Field<Byte> isstaying(Field<Integer> tableid) {
        Isstaying f = new Isstaying();
        f.setTableid(tableid);

        return f.asField();
    }

    /**
     * Call <code>coffeemilkteamanager.sp_GetDataSortedBy</code>
     */
    public static void spGetdatasortedby(Configuration configuration, String colName) {
        SpGetdatasortedby p = new SpGetdatasortedby();
        p.setColName(colName);

        p.execute(configuration);
    }
}
