/*
 * This file is generated by jOOQ.
*/
package BoBaPop.Model.tables;


import BoBaPop.Model.Coffeemilkteamanager;
import BoBaPop.Model.Indexes;
import BoBaPop.Model.Keys;
import BoBaPop.Model.tables.records.CustomersRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * InnoDB free: 6144 kB; (`CustomerTypeID`) REFER `coffeemilkteamanager/customertyp
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customers extends TableImpl<CustomersRecord> {

    private static final long serialVersionUID = -1740859569;

    /**
     * The reference instance of <code>coffeemilkteamanager.customers</code>
     */
    public static final Customers CUSTOMERS = new Customers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustomersRecord> getRecordType() {
        return CustomersRecord.class;
    }

    /**
     * The column <code>coffeemilkteamanager.customers.CustomerID</code>.
     */
    public final TableField<CustomersRecord, Integer> CUSTOMERID = createField("CustomerID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>coffeemilkteamanager.customers.CustomerTypeID</code>.
     */
    public final TableField<CustomersRecord, Integer> CUSTOMERTYPEID = createField("CustomerTypeID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>coffeemilkteamanager.customers.FullName</code>.
     */
    public final TableField<CustomersRecord, String> FULLNAME = createField("FullName", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>coffeemilkteamanager.customers.Age</code>.
     */
    public final TableField<CustomersRecord, Integer> AGE = createField("Age", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>coffeemilkteamanager.customers.PhoneNumber</code>.
     */
    public final TableField<CustomersRecord, String> PHONENUMBER = createField("PhoneNumber", org.jooq.impl.SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>coffeemilkteamanager.customers.Gender</code>.
     */
    public final TableField<CustomersRecord, Byte> GENDER = createField("Gender", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>coffeemilkteamanager.customers.Address</code>.
     */
    public final TableField<CustomersRecord, String> ADDRESS = createField("Address", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * Create a <code>coffeemilkteamanager.customers</code> table reference
     */
    public Customers() {
        this(DSL.name("customers"), null);
    }

    /**
     * Create an aliased <code>coffeemilkteamanager.customers</code> table reference
     */
    public Customers(String alias) {
        this(DSL.name(alias), CUSTOMERS);
    }

    /**
     * Create an aliased <code>coffeemilkteamanager.customers</code> table reference
     */
    public Customers(Name alias) {
        this(alias, CUSTOMERS);
    }

    private Customers(Name alias, Table<CustomersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Customers(Name alias, Table<CustomersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "InnoDB free: 6144 kB; (`CustomerTypeID`) REFER `coffeemilkteamanager/customertyp");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Coffeemilkteamanager.COFFEEMILKTEAMANAGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CUSTOMERS_CUSTOMERTYPEID, Indexes.CUSTOMERS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CustomersRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CUSTOMERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CustomersRecord> getPrimaryKey() {
        return Keys.KEY_CUSTOMERS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CustomersRecord>> getKeys() {
        return Arrays.<UniqueKey<CustomersRecord>>asList(Keys.KEY_CUSTOMERS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Customers as(String alias) {
        return new Customers(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Customers as(Name alias) {
        return new Customers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Customers rename(String name) {
        return new Customers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Customers rename(Name name) {
        return new Customers(name, null);
    }
}
