/*
 * This file is generated by jOOQ.
*/
package BoBaPop.Model.tables;


import BoBaPop.Model.Coffeemilkteamanager;
import BoBaPop.Model.tables.records.VwBilldetailsRecord;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VwBilldetails extends TableImpl<VwBilldetailsRecord> {

    private static final long serialVersionUID = 1756399114;

    /**
     * The reference instance of <code>coffeemilkteamanager.vw_billdetails</code>
     */
    public static final VwBilldetails VW_BILLDETAILS = new VwBilldetails();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VwBilldetailsRecord> getRecordType() {
        return VwBilldetailsRecord.class;
    }

    /**
     * The column <code>coffeemilkteamanager.vw_billdetails.BillID</code>.
     */
    public final TableField<VwBilldetailsRecord, Integer> BILLID = createField("BillID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>coffeemilkteamanager.vw_billdetails.OrderTime</code>.
     */
    public final TableField<VwBilldetailsRecord, Timestamp> ORDERTIME = createField("OrderTime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>coffeemilkteamanager.vw_billdetails.IsPaid</code>.
     */
    public final TableField<VwBilldetailsRecord, Byte> ISPAID = createField("IsPaid", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>coffeemilkteamanager.vw_billdetails.IsStaying</code>.
     */
    public final TableField<VwBilldetailsRecord, Byte> ISSTAYING = createField("IsStaying", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>coffeemilkteamanager.vw_billdetails.GrandTotal</code>.
     */
    public final TableField<VwBilldetailsRecord, Double> GRANDTOTAL = createField("GrandTotal", org.jooq.impl.SQLDataType.FLOAT, this, "");

    /**
     * The column <code>coffeemilkteamanager.vw_billdetails.TableID</code>.
     */
    public final TableField<VwBilldetailsRecord, Integer> TABLEID = createField("TableID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>coffeemilkteamanager.vw_billdetails.TableName</code>.
     */
    public final TableField<VwBilldetailsRecord, String> TABLENAME = createField("TableName", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>coffeemilkteamanager.vw_billdetails.CustomerID</code>.
     */
    public final TableField<VwBilldetailsRecord, Integer> CUSTOMERID = createField("CustomerID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>coffeemilkteamanager.vw_billdetails.CustomerTypeID</code>.
     */
    public final TableField<VwBilldetailsRecord, Integer> CUSTOMERTYPEID = createField("CustomerTypeID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>coffeemilkteamanager.vw_billdetails.FullName</code>.
     */
    public final TableField<VwBilldetailsRecord, String> FULLNAME = createField("FullName", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>coffeemilkteamanager.vw_billdetails.Age</code>.
     */
    public final TableField<VwBilldetailsRecord, Integer> AGE = createField("Age", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>coffeemilkteamanager.vw_billdetails.PhoneNumber</code>.
     */
    public final TableField<VwBilldetailsRecord, String> PHONENUMBER = createField("PhoneNumber", org.jooq.impl.SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>coffeemilkteamanager.vw_billdetails.Gender</code>.
     */
    public final TableField<VwBilldetailsRecord, Byte> GENDER = createField("Gender", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>coffeemilkteamanager.vw_billdetails.Address</code>.
     */
    public final TableField<VwBilldetailsRecord, String> ADDRESS = createField("Address", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>coffeemilkteamanager.vw_billdetails.CustomerTypeName</code>.
     */
    public final TableField<VwBilldetailsRecord, String> CUSTOMERTYPENAME = createField("CustomerTypeName", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * Create a <code>coffeemilkteamanager.vw_billdetails</code> table reference
     */
    public VwBilldetails() {
        this(DSL.name("vw_billdetails"), null);
    }

    /**
     * Create an aliased <code>coffeemilkteamanager.vw_billdetails</code> table reference
     */
    public VwBilldetails(String alias) {
        this(DSL.name(alias), VW_BILLDETAILS);
    }

    /**
     * Create an aliased <code>coffeemilkteamanager.vw_billdetails</code> table reference
     */
    public VwBilldetails(Name alias) {
        this(alias, VW_BILLDETAILS);
    }

    private VwBilldetails(Name alias, Table<VwBilldetailsRecord> aliased) {
        this(alias, aliased, null);
    }

    private VwBilldetails(Name alias, Table<VwBilldetailsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "VIEW");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Coffeemilkteamanager.COFFEEMILKTEAMANAGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBilldetails as(String alias) {
        return new VwBilldetails(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBilldetails as(Name alias) {
        return new VwBilldetails(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VwBilldetails rename(String name) {
        return new VwBilldetails(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VwBilldetails rename(Name name) {
        return new VwBilldetails(name, null);
    }
}
