/*
 * This file is generated by jOOQ.
*/
package BoBaPop.Model.tables.records;


import BoBaPop.Model.tables.Bills;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * InnoDB free: 6144 kB; (`CustomerID`) REFER `coffeemilkteamanager/customers`(`Cus
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BillsRecord extends UpdatableRecordImpl<BillsRecord> implements Record7<Integer, Integer, Timestamp, Double, Byte, Byte, Integer> {

    private static final long serialVersionUID = 1757687299;

    /**
     * Setter for <code>coffeemilkteamanager.bills.BillID</code>.
     */
    public void setBillid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.bills.BillID</code>.
     */
    public Integer getBillid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>coffeemilkteamanager.bills.CustomerID</code>.
     */
    public void setCustomerid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.bills.CustomerID</code>.
     */
    public Integer getCustomerid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>coffeemilkteamanager.bills.OrderTime</code>.
     */
    public void setOrdertime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.bills.OrderTime</code>.
     */
    public Timestamp getOrdertime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>coffeemilkteamanager.bills.GrandTotal</code>.
     */
    public void setGrandtotal(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.bills.GrandTotal</code>.
     */
    public Double getGrandtotal() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>coffeemilkteamanager.bills.IsPaid</code>.
     */
    public void setIspaid(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.bills.IsPaid</code>.
     */
    public Byte getIspaid() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>coffeemilkteamanager.bills.IsStaying</code>.
     */
    public void setIsstaying(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.bills.IsStaying</code>.
     */
    public Byte getIsstaying() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>coffeemilkteamanager.bills.TableID</code>.
     */
    public void setTableid(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.bills.TableID</code>.
     */
    public Integer getTableid() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Timestamp, Double, Byte, Byte, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Timestamp, Double, Byte, Byte, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Bills.BILLS.BILLID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Bills.BILLS.CUSTOMERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Bills.BILLS.ORDERTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return Bills.BILLS.GRANDTOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return Bills.BILLS.ISPAID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return Bills.BILLS.ISSTAYING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Bills.BILLS.TABLEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getBillid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getCustomerid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getOrdertime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getGrandtotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component5() {
        return getIspaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getIsstaying();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getTableid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getBillid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCustomerid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getOrdertime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getGrandtotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getIspaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getIsstaying();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getTableid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BillsRecord value1(Integer value) {
        setBillid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BillsRecord value2(Integer value) {
        setCustomerid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BillsRecord value3(Timestamp value) {
        setOrdertime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BillsRecord value4(Double value) {
        setGrandtotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BillsRecord value5(Byte value) {
        setIspaid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BillsRecord value6(Byte value) {
        setIsstaying(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BillsRecord value7(Integer value) {
        setTableid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BillsRecord values(Integer value1, Integer value2, Timestamp value3, Double value4, Byte value5, Byte value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BillsRecord
     */
    public BillsRecord() {
        super(Bills.BILLS);
    }

    /**
     * Create a detached, initialised BillsRecord
     */
    public BillsRecord(Integer billid, Integer customerid, Timestamp ordertime, Double grandtotal, Byte ispaid, Byte isstaying, Integer tableid) {
        super(Bills.BILLS);

        set(0, billid);
        set(1, customerid);
        set(2, ordertime);
        set(3, grandtotal);
        set(4, ispaid);
        set(5, isstaying);
        set(6, tableid);
    }
}
