/*
 * This file is generated by jOOQ.
*/
package BoBaPop.Model.tables.records;


import BoBaPop.Model.tables.Customers;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * InnoDB free: 6144 kB; (`CustomerTypeID`) REFER `coffeemilkteamanager/customertyp
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomersRecord extends UpdatableRecordImpl<CustomersRecord> implements Record7<Integer, Integer, String, Integer, String, Byte, String> {

    private static final long serialVersionUID = -278103329;

    /**
     * Setter for <code>coffeemilkteamanager.customers.CustomerID</code>.
     */
    public void setCustomerid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.customers.CustomerID</code>.
     */
    public Integer getCustomerid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>coffeemilkteamanager.customers.CustomerTypeID</code>.
     */
    public void setCustomertypeid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.customers.CustomerTypeID</code>.
     */
    public Integer getCustomertypeid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>coffeemilkteamanager.customers.FullName</code>.
     */
    public void setFullname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.customers.FullName</code>.
     */
    public String getFullname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>coffeemilkteamanager.customers.Age</code>.
     */
    public void setAge(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.customers.Age</code>.
     */
    public Integer getAge() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>coffeemilkteamanager.customers.PhoneNumber</code>.
     */
    public void setPhonenumber(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.customers.PhoneNumber</code>.
     */
    public String getPhonenumber() {
        return (String) get(4);
    }

    /**
     * Setter for <code>coffeemilkteamanager.customers.Gender</code>.
     */
    public void setGender(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.customers.Gender</code>.
     */
    public Byte getGender() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>coffeemilkteamanager.customers.Address</code>.
     */
    public void setAddress(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.customers.Address</code>.
     */
    public String getAddress() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, String, Integer, String, Byte, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, String, Integer, String, Byte, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Customers.CUSTOMERS.CUSTOMERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Customers.CUSTOMERS.CUSTOMERTYPEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Customers.CUSTOMERS.FULLNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Customers.CUSTOMERS.AGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Customers.CUSTOMERS.PHONENUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return Customers.CUSTOMERS.GENDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Customers.CUSTOMERS.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getCustomerid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getCustomertypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getFullname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getPhonenumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCustomerid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCustomertypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFullname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPhonenumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomersRecord value1(Integer value) {
        setCustomerid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomersRecord value2(Integer value) {
        setCustomertypeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomersRecord value3(String value) {
        setFullname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomersRecord value4(Integer value) {
        setAge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomersRecord value5(String value) {
        setPhonenumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomersRecord value6(Byte value) {
        setGender(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomersRecord value7(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomersRecord values(Integer value1, Integer value2, String value3, Integer value4, String value5, Byte value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomersRecord
     */
    public CustomersRecord() {
        super(Customers.CUSTOMERS);
    }

    /**
     * Create a detached, initialised CustomersRecord
     */
    public CustomersRecord(Integer customerid, Integer customertypeid, String fullname, Integer age, String phonenumber, Byte gender, String address) {
        super(Customers.CUSTOMERS);

        set(0, customerid);
        set(1, customertypeid);
        set(2, fullname);
        set(3, age);
        set(4, phonenumber);
        set(5, gender);
        set(6, address);
    }
}
