/*
 * This file is generated by jOOQ.
*/
package BoBaPop.Model.tables.records;


import BoBaPop.Model.tables.Customertypes;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * InnoDB free: 6144 kB
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomertypesRecord extends UpdatableRecordImpl<CustomertypesRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 386643110;

    /**
     * Setter for <code>coffeemilkteamanager.customertypes.CustomerTypeID</code>.
     */
    public void setCustomertypeid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.customertypes.CustomerTypeID</code>.
     */
    public Integer getCustomertypeid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>coffeemilkteamanager.customertypes.CustomerTypeName</code>.
     */
    public void setCustomertypename(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.customertypes.CustomerTypeName</code>.
     */
    public String getCustomertypename() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Customertypes.CUSTOMERTYPES.CUSTOMERTYPEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Customertypes.CUSTOMERTYPES.CUSTOMERTYPENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getCustomertypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCustomertypename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCustomertypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCustomertypename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomertypesRecord value1(Integer value) {
        setCustomertypeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomertypesRecord value2(String value) {
        setCustomertypename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomertypesRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomertypesRecord
     */
    public CustomertypesRecord() {
        super(Customertypes.CUSTOMERTYPES);
    }

    /**
     * Create a detached, initialised CustomertypesRecord
     */
    public CustomertypesRecord(Integer customertypeid, String customertypename) {
        super(Customertypes.CUSTOMERTYPES);

        set(0, customertypeid);
        set(1, customertypename);
    }
}
