/*
 * This file is generated by jOOQ.
*/
package BoBaPop.Model.tables.records;


import BoBaPop.Model.tables.VwBilldetails;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VwBilldetailsRecord extends TableRecordImpl<VwBilldetailsRecord> implements Record15<Integer, Timestamp, Byte, Byte, Double, Integer, String, Integer, Integer, String, Integer, String, Byte, String, String> {

    private static final long serialVersionUID = 443954989;

    /**
     * Setter for <code>coffeemilkteamanager.vw_billdetails.BillID</code>.
     */
    public void setBillid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_billdetails.BillID</code>.
     */
    public Integer getBillid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>coffeemilkteamanager.vw_billdetails.OrderTime</code>.
     */
    public void setOrdertime(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_billdetails.OrderTime</code>.
     */
    public Timestamp getOrdertime() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>coffeemilkteamanager.vw_billdetails.IsPaid</code>.
     */
    public void setIspaid(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_billdetails.IsPaid</code>.
     */
    public Byte getIspaid() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>coffeemilkteamanager.vw_billdetails.IsStaying</code>.
     */
    public void setIsstaying(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_billdetails.IsStaying</code>.
     */
    public Byte getIsstaying() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>coffeemilkteamanager.vw_billdetails.GrandTotal</code>.
     */
    public void setGrandtotal(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_billdetails.GrandTotal</code>.
     */
    public Double getGrandtotal() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>coffeemilkteamanager.vw_billdetails.TableID</code>.
     */
    public void setTableid(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_billdetails.TableID</code>.
     */
    public Integer getTableid() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>coffeemilkteamanager.vw_billdetails.TableName</code>.
     */
    public void setTablename(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_billdetails.TableName</code>.
     */
    public String getTablename() {
        return (String) get(6);
    }

    /**
     * Setter for <code>coffeemilkteamanager.vw_billdetails.CustomerID</code>.
     */
    public void setCustomerid(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_billdetails.CustomerID</code>.
     */
    public Integer getCustomerid() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>coffeemilkteamanager.vw_billdetails.CustomerTypeID</code>.
     */
    public void setCustomertypeid(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_billdetails.CustomerTypeID</code>.
     */
    public Integer getCustomertypeid() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>coffeemilkteamanager.vw_billdetails.FullName</code>.
     */
    public void setFullname(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_billdetails.FullName</code>.
     */
    public String getFullname() {
        return (String) get(9);
    }

    /**
     * Setter for <code>coffeemilkteamanager.vw_billdetails.Age</code>.
     */
    public void setAge(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_billdetails.Age</code>.
     */
    public Integer getAge() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>coffeemilkteamanager.vw_billdetails.PhoneNumber</code>.
     */
    public void setPhonenumber(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_billdetails.PhoneNumber</code>.
     */
    public String getPhonenumber() {
        return (String) get(11);
    }

    /**
     * Setter for <code>coffeemilkteamanager.vw_billdetails.Gender</code>.
     */
    public void setGender(Byte value) {
        set(12, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_billdetails.Gender</code>.
     */
    public Byte getGender() {
        return (Byte) get(12);
    }

    /**
     * Setter for <code>coffeemilkteamanager.vw_billdetails.Address</code>.
     */
    public void setAddress(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_billdetails.Address</code>.
     */
    public String getAddress() {
        return (String) get(13);
    }

    /**
     * Setter for <code>coffeemilkteamanager.vw_billdetails.CustomerTypeName</code>.
     */
    public void setCustomertypename(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_billdetails.CustomerTypeName</code>.
     */
    public String getCustomertypename() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, Timestamp, Byte, Byte, Double, Integer, String, Integer, Integer, String, Integer, String, Byte, String, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, Timestamp, Byte, Byte, Double, Integer, String, Integer, Integer, String, Integer, String, Byte, String, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VwBilldetails.VW_BILLDETAILS.BILLID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return VwBilldetails.VW_BILLDETAILS.ORDERTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return VwBilldetails.VW_BILLDETAILS.ISPAID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return VwBilldetails.VW_BILLDETAILS.ISSTAYING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return VwBilldetails.VW_BILLDETAILS.GRANDTOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return VwBilldetails.VW_BILLDETAILS.TABLEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return VwBilldetails.VW_BILLDETAILS.TABLENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return VwBilldetails.VW_BILLDETAILS.CUSTOMERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return VwBilldetails.VW_BILLDETAILS.CUSTOMERTYPEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return VwBilldetails.VW_BILLDETAILS.FULLNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return VwBilldetails.VW_BILLDETAILS.AGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return VwBilldetails.VW_BILLDETAILS.PHONENUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field13() {
        return VwBilldetails.VW_BILLDETAILS.GENDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return VwBilldetails.VW_BILLDETAILS.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return VwBilldetails.VW_BILLDETAILS.CUSTOMERTYPENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getBillid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getOrdertime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component3() {
        return getIspaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getIsstaying();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getGrandtotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getTableid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getTablename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getCustomerid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getCustomertypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getFullname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getPhonenumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component13() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getCustomertypename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getBillid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getOrdertime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getIspaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getIsstaying();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getGrandtotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getTableid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTablename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getCustomerid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getCustomertypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getFullname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getPhonenumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value13() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getCustomertypename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBilldetailsRecord value1(Integer value) {
        setBillid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBilldetailsRecord value2(Timestamp value) {
        setOrdertime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBilldetailsRecord value3(Byte value) {
        setIspaid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBilldetailsRecord value4(Byte value) {
        setIsstaying(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBilldetailsRecord value5(Double value) {
        setGrandtotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBilldetailsRecord value6(Integer value) {
        setTableid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBilldetailsRecord value7(String value) {
        setTablename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBilldetailsRecord value8(Integer value) {
        setCustomerid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBilldetailsRecord value9(Integer value) {
        setCustomertypeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBilldetailsRecord value10(String value) {
        setFullname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBilldetailsRecord value11(Integer value) {
        setAge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBilldetailsRecord value12(String value) {
        setPhonenumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBilldetailsRecord value13(Byte value) {
        setGender(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBilldetailsRecord value14(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBilldetailsRecord value15(String value) {
        setCustomertypename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwBilldetailsRecord values(Integer value1, Timestamp value2, Byte value3, Byte value4, Double value5, Integer value6, String value7, Integer value8, Integer value9, String value10, Integer value11, String value12, Byte value13, String value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VwBilldetailsRecord
     */
    public VwBilldetailsRecord() {
        super(VwBilldetails.VW_BILLDETAILS);
    }

    /**
     * Create a detached, initialised VwBilldetailsRecord
     */
    public VwBilldetailsRecord(Integer billid, Timestamp ordertime, Byte ispaid, Byte isstaying, Double grandtotal, Integer tableid, String tablename, Integer customerid, Integer customertypeid, String fullname, Integer age, String phonenumber, Byte gender, String address, String customertypename) {
        super(VwBilldetails.VW_BILLDETAILS);

        set(0, billid);
        set(1, ordertime);
        set(2, ispaid);
        set(3, isstaying);
        set(4, grandtotal);
        set(5, tableid);
        set(6, tablename);
        set(7, customerid);
        set(8, customertypeid);
        set(9, fullname);
        set(10, age);
        set(11, phonenumber);
        set(12, gender);
        set(13, address);
        set(14, customertypename);
    }
}
