/*
 * This file is generated by jOOQ.
*/
package BoBaPop.Model.tables.records;


import BoBaPop.Model.tables.VwItems;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VwItemsRecord extends TableRecordImpl<VwItemsRecord> implements Record9<Integer, Integer, Integer, Double, String, Double, byte[], Integer, String> {

    private static final long serialVersionUID = -86475759;

    /**
     * Setter for <code>coffeemilkteamanager.vw_items.BillID</code>.
     */
    public void setBillid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_items.BillID</code>.
     */
    public Integer getBillid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>coffeemilkteamanager.vw_items.DrinkID</code>.
     */
    public void setDrinkid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_items.DrinkID</code>.
     */
    public Integer getDrinkid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>coffeemilkteamanager.vw_items.Quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_items.Quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>coffeemilkteamanager.vw_items.Total</code>.
     */
    public void setTotal(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_items.Total</code>.
     */
    public Double getTotal() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>coffeemilkteamanager.vw_items.DrinkName</code>.
     */
    public void setDrinkname(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_items.DrinkName</code>.
     */
    public String getDrinkname() {
        return (String) get(4);
    }

    /**
     * Setter for <code>coffeemilkteamanager.vw_items.UnitPrice</code>.
     */
    public void setUnitprice(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_items.UnitPrice</code>.
     */
    public Double getUnitprice() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>coffeemilkteamanager.vw_items.Image</code>.
     */
    public void setImage(byte... value) {
        set(6, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_items.Image</code>.
     */
    public byte[] getImage() {
        return (byte[]) get(6);
    }

    /**
     * Setter for <code>coffeemilkteamanager.vw_items.DrinkTypeID</code>.
     */
    public void setDrinktypeid(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_items.DrinkTypeID</code>.
     */
    public Integer getDrinktypeid() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>coffeemilkteamanager.vw_items.DrinkTypeName</code>.
     */
    public void setDrinktypename(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>coffeemilkteamanager.vw_items.DrinkTypeName</code>.
     */
    public String getDrinktypename() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, Double, String, Double, byte[], Integer, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, Double, String, Double, byte[], Integer, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VwItems.VW_ITEMS.BILLID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return VwItems.VW_ITEMS.DRINKID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return VwItems.VW_ITEMS.QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return VwItems.VW_ITEMS.TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return VwItems.VW_ITEMS.DRINKNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return VwItems.VW_ITEMS.UNITPRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field7() {
        return VwItems.VW_ITEMS.IMAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return VwItems.VW_ITEMS.DRINKTYPEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return VwItems.VW_ITEMS.DRINKTYPENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getBillid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getDrinkid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDrinkname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return getUnitprice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component7() {
        return getImage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getDrinktypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getDrinktypename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getBillid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getDrinkid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDrinkname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getUnitprice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value7() {
        return getImage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getDrinktypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getDrinktypename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwItemsRecord value1(Integer value) {
        setBillid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwItemsRecord value2(Integer value) {
        setDrinkid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwItemsRecord value3(Integer value) {
        setQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwItemsRecord value4(Double value) {
        setTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwItemsRecord value5(String value) {
        setDrinkname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwItemsRecord value6(Double value) {
        setUnitprice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwItemsRecord value7(byte... value) {
        setImage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwItemsRecord value8(Integer value) {
        setDrinktypeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwItemsRecord value9(String value) {
        setDrinktypename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VwItemsRecord values(Integer value1, Integer value2, Integer value3, Double value4, String value5, Double value6, byte[] value7, Integer value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VwItemsRecord
     */
    public VwItemsRecord() {
        super(VwItems.VW_ITEMS);
    }

    /**
     * Create a detached, initialised VwItemsRecord
     */
    public VwItemsRecord(Integer billid, Integer drinkid, Integer quantity, Double total, String drinkname, Double unitprice, byte[] image, Integer drinktypeid, String drinktypename) {
        super(VwItems.VW_ITEMS);

        set(0, billid);
        set(1, drinkid);
        set(2, quantity);
        set(3, total);
        set(4, drinkname);
        set(5, unitprice);
        set(6, image);
        set(7, drinktypeid);
        set(8, drinktypename);
    }
}
